name = "pphi2N"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Pphi2N"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false

[[require]]
name = "pphi2"
scope = "mrdouglasny"
git = "https://github.com/mrdouglasny/pphi2.git"
rev = "4d82a22"

[[require]]
name = "MarkovSemigroups"
git = "https://github.com/jagg-ix/markov-semigroups.git"
rev = "2c4e1f843535ff4bc9016563515ab271abce621f"

[[lean_lib]]
name = "Pphi2N"
